# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rgateway.proto\x12\x10\x64\x65railed.gateway\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/empty.proto"/\n\x0bInterchange\x12\t\n\x01t\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x03\x12\t\n\x01\x64\x18\x03 \x01(\t"T\n\x0f\x42ulkInterchange\x12\t\n\x01t\x18\x01 \x01(\t\x12\x0c\n\x04uids\x18\x02 \x03(\x03\x12(\n\x01\x64\x18\x03 \x03(\x0b\x32\x1d.derailed.gateway.Interchange"\x17\n\tGuildInfo\x12\n\n\x02id\x18\x01 \x01(\x03"5\n\rGuildMetadata\x12\x11\n\tavailable\x18\x01 \x01(\x08\x12\x11\n\tpresences\x18\x02 \x01(\x05\x32\x9a\x01\n\x07Gateway\x12G\n\x0e\x64ispatch_guild\x12\x1d.derailed.gateway.Interchange\x1a\x16.google.protobuf.Empty\x12\x46\n\rdispatch_user\x12\x1d.derailed.gateway.Interchange\x1a\x16.google.protobuf.Emptyb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "gateway_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_INTERCHANGE"]._serialized_start = 91
    _globals["_INTERCHANGE"]._serialized_end = 138
    _globals["_BULKINTERCHANGE"]._serialized_start = 140
    _globals["_BULKINTERCHANGE"]._serialized_end = 224
    _globals["_GUILDINFO"]._serialized_start = 226
    _globals["_GUILDINFO"]._serialized_end = 249
    _globals["_GUILDMETADATA"]._serialized_start = 251
    _globals["_GUILDMETADATA"]._serialized_end = 304
    _globals["_GATEWAY"]._serialized_start = 307
    _globals["_GATEWAY"]._serialized_end = 461
# @@protoc_insertion_point(module_scope)
